### ISSUE TITLE
ac2tax directory needs to exist before prepareDatabase call

### ISSUE THREAD

**Issue by ressy** [guanxiangliang/liang2019#1]
If the ac2tax directory in input/database doesn't exist before running code/1.1.start.r (via liang2019.processed.sh), this error occurs in prepareDatabase:
```
eError in connection_connect(dbname, loadable.extensions, flags, vfs) :
  Could not connect to database:
unable to open database file
Calls: prepareDatabase ... new -> initialize -> initialize -> connection_connect
Execution halted
```

Something like `dir.create("input/database/ac2tax")` just before `prepareDatabase()` should avoid that, I think.

**Comment by guanxiangliang** [comment]
Fixed. Thanks!
